apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affine
  template:
    metadata:
      labels:
        app: affine
    spec:
      containers:
      - name: affine
        image: ghcr.io/MadhuPonnam66/affine:latest
        ports:
        - containerPort: 3000

